blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/MythologIQ/FailSafe/wiki
    about: Check our documentation before opening an issue.
  - name: Discussions
    url: https://github.com/MythologIQ/FailSafe/discussions
    about: Ask questions and discuss ideas.
